# install: kolab-ldap
# setup-kolab: ldap
# services: dirsrv dirsrv-admin
kolab-ldap:
  image: kvaps/kolab-ldap
  restart: always
  hostname: mail
  domainname: example.org
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - LDAP_ADMIN_PASS=<password>
    - LDAP_MANAGER_PASS=<password>
    - LDAP_CYRUS_PASS=<password>
    - LDAP_KOLAB_PASS=<password>
#  ports:
#    - 389:389

# install: kolab-mta 
# setup-kolab: mta
# services: postfix amavisservice clamavservice wallace
kolab-mta:
  image: kvaps/kolab-mta
  restart: always
  hostname: mail
  domainname: example.org
  links:
    - kolab-ldap
    - kolab-mysql
  volumes:
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "25:25"
    - 587:587

# install: kolab-imap
# setup-kolab: imap guam
# services: kolab-saslauthd cyrus-imapd guam
kolab-imap:
  image: kvaps/kolab-imap
  restart: always
  hostname: mail
  domainname: example.org
  links:
    - kolab-ldap
  volumes:
    - /etc/localtime:/etc/localtime:ro
  ports:
#    - 110:110
#    - 995:995
    - 143:143
    - 993:993
    - 4190:4190

# install: kolab-server
# setup-kolab: kolabd
# services: kolab-server kolabd
kolab-kolabd:
  image: kvaps/kolab-kolabd
  restart: always
  hostname: mail
  domainname: example.org
  links:
    - kolab-kolabd-db:mysql
    - kolab-ldap
    - kolab-imap
  volumes:
    - /etc/localtime:/etc/localtime:ro

# install: mariadb-server
# setup-kolab: mysql
# services: mysql
kolab-kolabd-db:
  image: kvaps/kolab-mysql
  restart: always
  hostname: mail
  domainname: example.org
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MYSQL_ROOT_PASS=<password>
    - MYSQL_USER=kolab
    - MYSQL_DATABASE=kolab
    - MYSQL_PASSWORD=<password>

# install: kolab-webclient kolab-webadmin
# setup-kolab: php roundcube syncroton
# services: httpd (roundcubemail kolab-syncroton kolab-freebusy webadmin hosted-kolab irony chwala kolab-autoconf)
kolab-roundcube:
  image: kvaps/kolab-httpd
  restart: always
  hostname: mail
  domainname: example.org
  links:
    - kolab-ldap
    - kolab-roundcube-db:mysql
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MYSQL_PASSWORD=<password>
  ports:
    - 80:80
    - 443:443

# install: mariadb-server 
# setup-kolab:
# services: mysql
kolab-roundcube-db:
  image: kvaps/kolab-mysql
  restart: always
  hostname: mail
  domainname: example.org
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MYSQL_ROOT_PASS=<password>

# install: manticore 
# setup-kolab: manticore
# services: mongod manticore
kolab-manticore:
  image: kvaps/kolab-ldap
  restart: always
  hostname: mail
  domainname: example.org
  links:
    - kolab-ldap
  volumes:
    - /etc/localtime:/etc/localtime:ro
  ports:
    - 8080:8080
